version: "3.5"

services:
  test-db:
    container_name: test-db
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5429:5432"
